---
  - name: copy the csv yml to vars in current task
    command: cp ./input.csv.yml ./roles/infrastructure/vars/input.csv

  - name: select file
    script: ./roles/infrastructure/tasks/Bridge.sh "{{Name_src_container1}}" "{{Name_destination_container2}}"
    when: ("{{Network_type0}}" == "Bridge")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/Bridge.sh "{{Name_src_container4}}" "{{Name_destination_container5}}"
    when: ("{{Network_type3}}" == "Bridge")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/Bridge.sh "{{Name_src_container7}}" "{{Name_destination_container8}}"
    when: ("{{Network_type6}}" == "Bridge")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/Bridge.sh "{{Name_src_container10}}" "{{Name_destination_container11}}"
    when: ("{{Network_type9}}" == "Bridge")
    become: yes
#------------------------------------------------------------------------------------------------------------------
  - name: select file
    script: ./roles/infrastructure/tasks/VXLAN.sh "{{Name_src_container1}}" "{{Name_destination_container2}}"
    when: ("{{Network_type0}}" == "VXLAN")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/VXLAN.sh "{{Name_src_container4}}" "{{Name_destination_container5}}"
    when: ("{{Network_type3}}" == "VXLAN")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/VXLAN.sh "{{Name_src_container7}}" "{{Name_destination_container8}}"
    when: ("{{Network_type6}}" == "VXLAN")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/VXLAN.sh "{{Name_src_container10}}" "{{Name_destination_container11}}"
    when: ("{{Network_type9}}" == "VXLAN")
    become: yes
#------------------------------------------------------------------------------------------------------------------
  - name: select file
    script: ./roles/infrastructure/tasks/L3.sh "{{Name_src_container1}}" "{{Name_destination_container2}}"
    when: ("{{Network_type0}}" == "L3")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/L3.sh "{{Name_src_container4}}" "{{Name_destination_container5}}"
    when: ("{{Network_type3}}" == "L3")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/L3.sh "{{Name_src_container7}}" "{{Name_destination_container8}}"
    when: ("{{Network_type6}}" == "L3")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/L3.sh "{{Name_src_container10}}" "{{Name_destination_container11}}"
    when: ("{{Network_type9}}" == "L3")
    become: yes
#------------------------------------------------------------------------------------------------------------------
  - name: select file
    script: ./roles/infrastructure/tasks/GRE.sh "{{Name_src_container1}}" "{{Name_destination_container2}}"
    when: ("{{Network_type0}}" == "GRE")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/GRE.sh "{{Name_src_container4}}" "{{Name_destination_container5}}"
    when: ("{{Network_type3}}" == "GRE")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/GRE.sh "{{Name_src_container7}}" "{{Name_destination_container8}}"
    when: ("{{Network_type6}}" == "GRE")
    become: yes

  - name: select file
    script: ./roles/infrastructure/tasks/GRE.sh "{{Name_src_container10}}" "{{Name_destination_container11}}"
    when: ("{{Network_type9}}" == "GRE")
    become: yes
#------------------------------------------------------------------------------------------------------------------
