---
  - name: creating network to be used for everything
    command: sudo docker network create --subnet=172.18.0.0/16 q2Network

  - name: create containers LC1
    command: sudo docker run -itd --privileged --name=LC1 --hostname=LC1 --net q2Network --ip 172.18.0.12 ubuntu

  - name: creating network to be used for everything
    command: sudo docker network create --subnet=172.19.0.0/16 q3Network

  - name: create containers LC2
    command: sudo docker run -itd --privileged --name=LC2 --hostname=LC2 --net q3Network --ip 172.19.0.13 ubuntu

  - name: creating network to be used for everything
    command: sudo docker network create --subnet=172.20.0.0/16 q4Network

  - name: create containers SC1
    command: sudo docker run -itd --privileged --name=SC1 --hostname=SC1 --net q4Network --ip 172.20.0.14 ubuntu

  - name: creating network to be used for everything
    command: sudo docker network create --subnet=172.21.0.0/16 q5Network

  - name: create containers SC2
    command: sudo docker run -itd --privileged --name=SC2 --hostname=SC2 --net q5Network --ip 172.21.0.15 ubuntu
