---
  - name: create containers LC1, LC2, SC1, SC2
    command: sudo docker run -itd --privileged --name="{{ item }}" --hostname="{{ item }}" ubuntu
    with_items:
      - LC1
      - LC2
      - SC1
      - SC2

  - name: create Veth pair
    command: sudo ip link add "{{Name_destination_container}}_{{Network_type}}" type veth peer name "{{Network_type}}_{{Name_destination_container}}"
  
  - name: detect process id of the container
    command: sudo docker inspect -f {{.State.Pid}} "{{Name_destination_container}}"
    register: pid
  
  - name: make interface up
    command: sudo ip link set testif netns "{{pid.stdout}}"
